name: Make Python release package

on:
  release:
    type: created
  workflow_dispatch:

permissions: read

jobs:
  build-package:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '>= 3.11'

      - name: Build Python package
        run: |
          python -m pip install build
          python -m build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-dist
          path: dist/*

      - name: Upload package to release
        if: ${{ github.ref_type == 'tag' }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_TAG: ${{ github.ref_name }}
        run: |
          gh release upload $RELEASE_TAG dist/* --clobber
